#pragma once
/*
	This is borderline garbage and needs to be reworked.
*/
#define ZIPFS_ERRSTR_CANNOT_LOCATE_NAME				"cannot locate name."
#define ZIPFS_ERRSTR_FILE_CANNOT_READ_SIZE			"file stat.size is not valid. cannot read size."
#define ZIPFS_ERRSTR_FILE_CANNOT_READ_ALL			"file read length != file length."
#define ZIPFS_ERRSTR_FILE_CANNOT_CLOSE				"couldn't close file'."
#define ZIPFS_ERRSTR_SOURCE_STAT_SIZE_NOT_VALID		"source stat.size is not valid. cannot read size."
#define ZIPFS_ERRSTR_SOURCE_CANNOT_READ_ALL			"source read length != source length."
#define ZIPFS_ERRSTR_ARCHIVE_IS_NULL				"archive is null."
#define ZIPFS_ERRSTR_FILE_ALREADY_EXISTS			"file already exists."
#define ZIPFS_ERRSTR_ERROR_WRITING_TO_OUTPUT_FILE	"there was an error writing to output file."
#define ZIPFS_ERRSTR_PARENT_PATH_DOESNT_EXIST		"parent path doesn't exist."
#define ZIPFS_ERRSTR_ZIPFS_INDEX_ERROR				"zipfs_index error."
#define ZIPFS_ERRSTR_FS_PATH_DOESNT_EXIST			"filesystem path doesn't exist."
#define ZIPFS_ERRSTR_FS_PATH_NOT_A_REGULAR_FILE		"filesystem path is not a regular file."
#define ZIPFS_ERRSTR_FILE_PATH_EXPECTED				"file path expected."
#define ZIPFS_ERRSTR_FILE_PATHS_EXPECTED			"file paths expected."
#define ZIPFS_ERRSTR_DIRECTORY_PATH_EXPECTED		"directory path expected."
#define ZIPFS_ERRSTR_DIRECTORY_PATHS_EXPECTED		"directory paths expected."
#define ZIPFS_ERRSTR_DIRECTORY_BAD_TARGET			"target doesn't exist or is not a directory."
#define ZIPFS_ERRSTR_SOURCE_DIR_DOESNT_EXIST		"source directory doesn't exist."
#define ZIPFS_ERRSTR_COULD_NOT_CREATE_DIR			"could not create directory."
#define ZIPFS_ERRSTR_TARGET_FILE_ALREADY_EXISTS		"target file already exists."
#define ZIPFS_ERRSTR_TARGET_FILE_DOESNT_EXIST		"target file doesn't exist."